### ISSUE TITLE
Why are some enchants in /skyblock/enchants.json "goodLevel" 0?

### ISSUE THREAD

**Issue by ENORMOUZ** [BiscuitDevelopment/SkyblockAddons-Data#7]
While viewing the file in https://github.com/BiscuitDevelopment/SkyblockAddons-Data/blob/main/skyblock/enchants.json, I noticed that some enchantments have their "goodLevel" set as 0. Is this intended, or should this be fixed?

**Comment by ENORMOUZ** [comment]
For example, in "NORMAL", "overload" and "vicious", and in "ULTIMATE", every single enchant.

**Comment by Pndablob** [comment]
"goodLevel":
> is the maximum level you can craft from an enchanting table

some enchants, such as smarty pants, overload, vicious, etc; and all ultimate enchants can not be obtained from an enchanting table, they have a "goodLevel" of 0.

**Comment by ENORMOUZ** [comment]
Oh, okay. I will close this issue now.
